version: "3.7"

services:
  instagram-analyzer:
    image: pedroleonpython/instagram-analyzer-saas:latest
    networks:
      - unfeknet
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_APIFY_API_TOKEN=${VITE_APIFY_API_TOKEN}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.instagram-analyzer.rule=Host(`spot.unfek.com.br`)
        - traefik.http.routers.instagram-analyzer.entrypoints=websecure
        - traefik.http.routers.instagram-analyzer.tls.certresolver=letsencryptresolver
        - traefik.http.services.instagram-analyzer.loadbalancer.server.port=80
        - traefik.http.services.instagram-analyzer.loadbalancer.passHostHeader=true

networks:
  unfeknet:
    external: true
